### ISSUE TITLE
CPU Affinity?

### ISSUE THREAD

**Issue by ShayBox** [BlueberryWolf/SetVRChatPriority#3]
Is there a way to also set CPU affinity? VRChat seems to use thread #'s 8-15 out of 32 for me, which is less than ideal, but I can't change it because of EAC.

**Comment by ShayBox** [comment]
I don't believe there's a way to set affinity with the registry, but I found if you change the affinity of steam.exe, it'll apply to any game launched by steam. It's less than ideal but it works.

Probably not something this program would do as it needs to be constantly running to set the steam affinity, but you can use Process Lasso or any other similar program.

**Comment by BlueberryWolf** [comment]
I only just saw this now.  It is actually possible to set the affinity that VRChat launches with via the [VRChat launch options](https://docs.vrchat.com/docs/launch-options), which can be configured in the launch options within the properties of VRChat in steam.  The particular launch option is `--affinity=bitmask`, where the bitmask can be calculated via an [Affinity Mask Calculator](https://bitsum.com/tools/cpu-affinity-calculator)
